.\" This is a comment
.\" Contact gburd@acm.org
.TH man 1 "16 Nov 2011" ".1" "fsblksz"
.SH NAME
fsblksz \- Filesystem Block Size
.SH SYNOPSIS
Determin the blocksize for a given filesystem
.SH DESCRIPTION
Outputs the block size for the filesystem give a path.
.SH OPTIONS
Without arguments the blocksize for the root filesystem is output.
.SH SEE ALSO
.SH BUGS
No known bugs for this template, except you might want to replace the quotes if
you copy from my blog.
.SH AUTHOR
Greg Burd <gburd@acm.org>
